/* BudgetCook V1 — application state and UI controller */
"use strict";

const STORAGE_KEY = "budgetcook_v1";
const MEALS = ["breakfast", "lunch", "snack", "dinner"];
const MEAL_LABELS = { breakfast: "🌅 Petit-déjeuner", lunch: "☀️ Déjeuner", snack: "🍎 Collation", dinner: "🌙 Dîner" };
const DAYS = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"];

const DEFAULT_PROFILE = {
  name: "", age: 20, sex: "male", height: 179, weight: 88, bodyFat: 30,
  chest: 0, waist: 0, hips: 0, arm: 0, thigh: 0, neck: 0,
  trainingDays: 5, activity: "active", goal: "recomp", targetWeight: 80,
  targetBodyFat: 15, deficit: 300, proteinPerKg: 2, fatPerKg: 0.8,
  budget: 50, store: "", preferences: { autoGenerate: false, budgetOptimization: true, highProtein: true }
};

function clone(value) { return JSON.parse(JSON.stringify(value)); }
function newDay() { return { breakfast: [], lunch: [], snack: [], dinner: [] }; }
function defaultPlanner() { return DAYS.map((day, index) => ({ day, index, meals: newDay() })); }
function defaultState() { return { version: 1, profile: clone(DEFAULT_PROFILE), journal: {}, planner: defaultPlanner(), recipes: [], shopping: [], pantry: [], progress: [] }; }
function id(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }
function number(value, fallback = 0) { const result = Number(value); return Number.isFinite(result) ? result : fallback; }
function round(value, precision = 1) { const p = 10 ** precision; return Math.round(number(value) * p) / p; }
function dateKey(date = new Date()) { return date.toISOString().slice(0, 10); }
function escapeHtml(value) { const node = document.createElement("span"); node.textContent = String(value ?? ""); return node.innerHTML; }
function byId(value) { return document.getElementById(value); }
function setText(target, value) { const node = typeof target === "string" ? byId(target) : target; if (node) node.textContent = value; }
function format(value, digits = 0) { return new Intl.NumberFormat("fr-FR", { maximumFractionDigits: digits, minimumFractionDigits: digits }).format(number(value)); }
function euro(value) { return `${format(value, 2)} €`; }

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return defaultState();
    const saved = JSON.parse(raw);
    const fallback = defaultState();
    const profile = { ...fallback.profile, ...(saved.profile || {}), preferences: { ...fallback.profile.preferences, ...(saved.profile?.preferences || {}) } };
    const planner = Array.isArray(saved.planner) && saved.planner.length === 7 ? saved.planner.map((day, index) => ({ day: DAYS[index], index, meals: normalizeDay(day.meals) })) : fallback.planner;
    const journal = saved.journal && !Array.isArray(saved.journal) ? Object.fromEntries(Object.entries(saved.journal).map(([key, day]) => [key, normalizeDay(day)])) : {};
    return { ...fallback, ...saved, version: 1, profile, journal, planner, recipes: Array.isArray(saved.recipes) ? saved.recipes : [], shopping: Array.isArray(saved.shopping) ? saved.shopping : [], pantry: Array.isArray(saved.pantry) ? saved.pantry : [], progress: Array.isArray(saved.progress) ? saved.progress : [] };
  } catch (_) { return defaultState(); }
}
function normalizeDay(day) { const result = newDay(); MEALS.forEach(meal => { result[meal] = Array.isArray(day?.[meal]) ? day[meal].filter(item => item && item.foodId && number(item.grams) > 0).map(item => ({ id: item.id || id("meal"), foodId: item.foodId, grams: round(item.grams) })) : []; }); return result; }
let state = loadState();
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }

function foods() { return typeof FOODS !== "undefined" && Array.isArray(FOODS) ? FOODS : []; }
function food(foodId) { return foods().find(item => item.id === foodId) || null; }
function nutrition(foodId, grams) { const item = food(foodId); const factor = Math.max(0, number(grams)) / 100; return item ? { kcal: round(item.kcal * factor), protein: round(item.protein * factor), carbs: round(item.carbs * factor), fat: round(item.fat * factor), price: round(number(item.price) * factor, 2) } : { kcal: 0, protein: 0, carbs: 0, fat: 0, price: 0 }; }
function totals(items) { return (items || []).reduce((sum, item) => { const value = nutrition(item.foodId, item.grams); sum.kcal += value.kcal; sum.protein += value.protein; sum.carbs += value.carbs; sum.fat += value.fat; sum.price += value.price; return sum; }, { kcal: 0, protein: 0, carbs: 0, fat: 0, price: 0 }); }
function dailyTotals(day = currentDay()) { return totals(MEALS.flatMap(meal => day[meal] || [])); }
function targets(profile = state.profile) {
  const weight = Math.max(1, number(profile.weight, 88));
  const height = Math.max(1, number(profile.height, 179));
  const age = Math.max(1, number(profile.age, 20));
  const bmr = profile.sex === "female" ? 10 * weight + 6.25 * height - 5 * age - 161 : 10 * weight + 6.25 * height - 5 * age + 5;
  const adjustment = ["gain", "bulk"].includes(profile.goal) ? Math.abs(number(profile.surplus, 250)) : profile.goal === "maintain" ? 0 : -Math.abs(number(profile.deficit, 300));
  const factors = { sedentary: 1.2, light: 1.375, moderate: 1.55, active: 1.725, very_active: 1.9 };
  const calories = Math.max(1200, Math.round(bmr * (factors[profile.activity] || number(profile.activity, 1.725)) + adjustment));
  const protein = Math.max(0, number(profile.proteinPerKg, 2) * weight);
  const fat = Math.max(0, number(profile.fatPerKg, .8) * weight);
  const carbs = Math.max(0, (calories - protein * 4 - fat * 9) / 4);
  return { calories, protein: round(protein), fat: round(fat), carbs: round(carbs), bmr: Math.round(bmr) };
}
function currentDay() { const key = dateKey(); if (!state.journal[key]) state.journal[key] = newDay(); return state.journal[key]; }
function toast(message, type = "info") { const container = byId("toastContainer"); if (!container) return; const item = document.createElement("div"); item.className = `toast toast-${type}`; item.textContent = message; container.appendChild(item); requestAnimationFrame(() => item.classList.add("show")); setTimeout(() => { item.classList.remove("show"); setTimeout(() => item.remove(), 250); }, 2600); }
function openModal(content) { byId("modalContent").innerHTML = content; byId("modalOverlay").classList.remove("hidden"); document.body.classList.add("modal-open"); }
function closeModal() { byId("modalOverlay")?.classList.add("hidden"); document.body.classList.remove("modal-open"); }

function recipeNutrition(recipe) { return totals((recipe.ingredients || []).map(item => ({ foodId: item.foodId || item.food, grams: item.grams }))); }
function recipes() {
  const source = typeof RECIPES !== "undefined" && Array.isArray(RECIPES) ? RECIPES : [];
  const all = [...source, ...state.recipes]; const seen = new Set();
  return all.filter(recipe => recipe?.id && !seen.has(recipe.id) && seen.add(recipe.id));
}
function addFood(foodId, grams, meal = "lunch", day = currentDay()) { if (!food(foodId) || !MEALS.includes(meal)) return false; day[meal].push({ id: id("meal"), foodId, grams: Math.max(1, round(grams)) }); saveState(); render(); return true; }
function updateFood(meal, itemId, grams) { const item = currentDay()[meal]?.find(entry => entry.id === itemId); if (!item) return; item.grams = Math.max(1, round(grams)); saveState(); render(); }
function removeFood(meal, itemId) { const day = currentDay(); day[meal] = day[meal].filter(item => item.id !== itemId); saveState(); render(); }

function navigate(page) { document.querySelectorAll(".page").forEach(node => node.classList.toggle("active", node.id === `page-${page}`)); document.querySelectorAll("[data-page]").forEach(node => node.classList.toggle("active", node.dataset.page === page)); document.querySelector(".sidebar")?.classList.remove("mobile-open"); }
function renderMacro(prefix, consumed, target) { setText(`${prefix}Consumed`, format(consumed)); setText(`${prefix}Target`, format(target)); const progress = byId(`${prefix}Progress`); if (progress) progress.style.width = `${Math.min(100, target ? consumed / target * 100 : 0)}%`; }
function renderHome() { const total = dailyTotals(); const goal = targets(); setText("homeCaloriesConsumed", format(total.kcal)); setText("homeCaloriesTarget", format(goal.calories)); setText("homeCaloriesRemaining", `${format(Math.max(0, goal.calories - total.kcal))} kcal restants`); setText("homeCaloriesPercent", `${format(goal.calories ? total.kcal / goal.calories * 100 : 0)}%`); const circle = byId("homeCaloriesProgress"); if (circle) circle.style.setProperty("--progress", `${Math.min(100, total.kcal / goal.calories * 100)}%`); renderMacro("homeProtein", total.protein, goal.protein); renderMacro("homeCarbs", total.carbs, goal.carbs); renderMacro("homeFat", total.fat, goal.fat); setText("homeBudget", euro(total.price)); setText("homeWeight", `${format(state.profile.weight, 1)} kg`); const preview = byId("todayMeals"); if (preview) { const items = MEALS.flatMap(meal => currentDay()[meal].map(item => ({ meal, item }))); preview.innerHTML = items.length ? items.map(({ meal, item }) => { const entry = food(item.foodId); return `<div class="meal-item"><span>${entry?.emoji || "🍽️"}</span><div><strong>${escapeHtml(entry?.name || "Aliment")}</strong><small>${MEAL_LABELS[meal]} · ${format(item.grams)} g</small></div><strong>${format(nutrition(item.foodId, item.grams).kcal)} kcal</strong></div>`; }).join("") : `<div class="empty-state"><p>Aucun repas enregistré aujourd'hui.</p></div>`; } }
function renderJournal() { const total = dailyTotals(); const goal = targets(); [["Calories", "kcal"], ["Protein", "protein"], ["Carbs", "carbs"], ["Fat", "fat"]].forEach(([label, key]) => { setText(`journal${label}`, format(total[key])); setText(`journal${label}Target`, format(goal[key])); }); MEALS.forEach(meal => { const items = currentDay()[meal]; const container = byId(`${meal}Items`); setText(`${meal}Calories`, `${format(totals(items).kcal)} kcal`); if (!container) return; container.innerHTML = items.length ? items.map(item => mealItemHtml(meal, item)).join("") : `<div class="meal-empty"><span>Aucun aliment ajouté</span></div>`; }); }
function mealItemHtml(meal, item) { const entry = food(item.foodId); const value = nutrition(item.foodId, item.grams); return `<div class="meal-item"><div class="meal-item-info"><span class="meal-item-icon">${entry?.emoji || "🍽️"}</span><div><strong>${escapeHtml(entry?.name || "Aliment")}</strong><span>${format(item.grams)} g · ${format(value.kcal)} kcal · P ${format(value.protein)} g</span></div></div><div class="meal-item-actions"><button type="button" class="icon-button-small" data-edit-item="${item.id}" data-meal="${meal}" aria-label="Modifier">✏️</button><button type="button" class="icon-button-small danger" data-remove-item="${item.id}" data-meal="${meal}" aria-label="Supprimer">×</button></div></div>`; }
function renderRecipes() { const container = byId("recipesGrid"); if (!container) return; const query = String(byId("recipeSearch")?.value || "").trim().toLocaleLowerCase("fr"); const goal = byId("recipeGoalFilter")?.value || ""; const filtered = recipes().filter(recipe => (!query || recipe.name.toLocaleLowerCase("fr").includes(query)) && (!goal || goal === "all" || recipe.goal === goal)); container.innerHTML = filtered.length ? filtered.map(recipe => recipeHtml(recipe)).join("") : `<div class="empty-state"><p>Aucune recette trouvée.</p></div>`; }
function recipeHtml(recipe) { const value = recipeNutrition(recipe); return `<article class="recipe-card"><div class="recipe-image">${recipe.emoji || "🍳"}</div><div class="recipe-content"><h3>${escapeHtml(recipe.name)}</h3><p>${escapeHtml(recipe.category || "Recette")}</p><div class="recipe-macros"><span>${format(value.kcal)} kcal</span><span>P ${format(value.protein)} g</span><span>G ${format(value.carbs)} g</span></div><div class="recipe-actions"><button type="button" class="secondary-button" data-recipe-detail="${recipe.id}">Voir</button><button type="button" class="primary-button" data-recipe-add="${recipe.id}">Ajouter</button></div></div></article>`; }
function plannerTotals() { return state.planner.reduce((sum, day) => { const value = dailyTotals(day.meals); sum.kcal += value.kcal; sum.protein += value.protein; sum.price += value.price; return sum; }, { kcal: 0, protein: 0, price: 0 }); }
function renderPlanner() { const container = byId("weekPlanner"); if (!container) return; container.innerHTML = state.planner.map((day, index) => { const value = dailyTotals(day.meals); return `<section class="planner-day"><div class="planner-day-header"><strong>${day.day}</strong><span>${format(value.kcal)} kcal · P ${format(value.protein)} g</span></div>${MEALS.map(meal => `<div class="planner-meal"><strong>${MEAL_LABELS[meal]}</strong><div>${day.meals[meal].length ? day.meals[meal].map(item => `${escapeHtml(food(item.foodId)?.name || "Aliment")} (${format(item.grams)} g)`).join(", ") : "Aucun aliment"}</div><button type="button" class="add-small-button" data-planner-add="${meal}" data-planner-day="${index}">+</button></div>`).join("")}</section>`; }).join(""); const value = plannerTotals(); setText("plannerAverageCalories", `${format(value.kcal / 7)} kcal`); setText("plannerAverageProtein", `${format(value.protein / 7)} g`); setText("plannerBudget", euro(value.price)); }
function renderProfile() { const p = state.profile; const fields = { profileName: p.name, profileAge: p.age, profileSex: p.sex, profileHeight: p.height, profileWeight: p.weight, profileBodyFat: p.bodyFat, profileChest: p.chest, profileWaist: p.waist, profileHips: p.hips, profileArm: p.arm, profileThigh: p.thigh, profileNeck: p.neck, profileTraining: p.trainingDays, profileActivity: p.activity, profileTargetWeight: p.targetWeight, profileTargetBodyFat: p.targetBodyFat, profileDeficit: p.deficit, proteinTarget: p.proteinPerKg, fatTarget: p.fatPerKg, profileBudget: p.budget, profileStore: p.store }; Object.entries(fields).forEach(([key, value]) => { const node = byId(key); if (node) node.value = value ?? ""; }); const selectedGoal = document.querySelector(`input[name="profileGoal"][value="${p.goal}"]`); if (selectedGoal) selectedGoal.checked = true; ["preferenceAutoGenerate", "preferenceBudgetOptimization", "preferenceHighProtein"].forEach(key => { const node = byId(key); if (node) node.checked = Boolean(p.preferences[key.replace("preference", "").replace(/^./, char => char.toLowerCase())]); }); const goal = targets(); setText("calculatedCarbs", `${format(goal.carbs)} g`); setText("profileCalculatedCalories", `${format(goal.calories)} kcal`); setText("profileCalculatedProtein", `${format(goal.protein)} g`); setText("profileCalculatedFat", `${format(goal.fat)} g`); setText("profileCalculatedCarbs", `${format(goal.carbs)} g`); }
function renderCoach() { const total = dailyTotals(); const goal = targets(); setText("coachCaloriesText", `${format(total.kcal)} / ${format(goal.calories)} kcal`); setText("coachProteinText", `${format(total.protein)} / ${format(goal.protein)} g`); setText("coachBudgetText", `${euro(total.price)} aujourd'hui`); setText("coachFoodQualityText", total.protein >= goal.protein ? "Objectif protéines atteint." : "Ajoute une source de protéines."); const list = byId("coachRecommendations"); if (list) list.innerHTML = `<li>${total.kcal < goal.calories * .8 ? "Ton apport est bas : complète tes repas." : "Ton apport calorique est suivi."}</li><li>${total.protein < goal.protein ? "Privilégie poulet, thon, œufs ou skyr." : "Très bon apport en protéines."}</li>`; }
function render() { renderHome(); renderJournal(); renderRecipes(); renderPlanner(); renderProfile(); renderCoach(); }

function openFoodPicker({ meal = "lunch", plannerDay = null } = {}) { const options = foods().map(item => `<option value="${item.id}">${escapeHtml(item.name)} — ${item.kcal} kcal/100 g</option>`).join(""); openModal(`<div class="modal-header"><h2>Ajouter un aliment</h2><p>Choisis l'aliment et la quantité.</p></div><div class="form-group"><label for="foodPickerSelect">Aliment</label><select id="foodPickerSelect">${options}</select></div><div class="form-group"><label for="foodPickerGrams">Quantité en grammes</label><input id="foodPickerGrams" type="number" min="1" value="100"></div><div class="form-group"><label for="foodPickerMeal">Repas</label><select id="foodPickerMeal">${MEALS.map(value => `<option value="${value}" ${value === meal ? "selected" : ""}>${MEAL_LABELS[value]}</option>`).join("")}</select></div><div class="modal-actions"><button type="button" class="secondary-button" id="cancelFoodPicker">Annuler</button><button type="button" class="primary-button" id="confirmFoodPicker">Ajouter</button></div>`); byId("cancelFoodPicker").addEventListener("click", closeModal); byId("confirmFoodPicker").addEventListener("click", () => { const foodId = byId("foodPickerSelect").value; const grams = number(byId("foodPickerGrams").value); const selectedMeal = byId("foodPickerMeal").value; if (!foodId || grams <= 0) return toast("Indique une quantité valide.", "error"); if (plannerDay === null) addFood(foodId, grams, selectedMeal); else { state.planner[plannerDay].meals[selectedMeal].push({ id: id("plan"), foodId, grams: round(grams) }); saveState(); render(); } closeModal(); toast("Aliment ajouté.", "success"); }); }
function openEditPicker(meal, itemId) { const item = currentDay()[meal].find(entry => entry.id === itemId); if (!item) return; openModal(`<div class="modal-header"><h2>Modifier la quantité</h2></div><div class="form-group"><label for="editGrams">Quantité en grammes</label><input id="editGrams" type="number" min="1" value="${item.grams}"></div><div class="modal-actions"><button type="button" class="secondary-button" id="cancelEdit">Annuler</button><button type="button" class="primary-button" id="saveEdit">Enregistrer</button></div>`); byId("cancelEdit").addEventListener("click", closeModal); byId("saveEdit").addEventListener("click", () => { const grams = number(byId("editGrams").value); if (grams <= 0) return toast("Indique une quantité valide.", "error"); updateFood(meal, itemId, grams); closeModal(); toast("Quantité mise à jour.", "success"); }); }
function openRecipeDetail(recipeId) { const recipe = recipes().find(item => item.id === recipeId); if (!recipe) return; const value = recipeNutrition(recipe); openModal(`<div class="modal-header"><h2>${escapeHtml(recipe.name)}</h2><p>${escapeHtml(recipe.category || "Recette")}</p></div><div class="recipe-macros"><span>${format(value.kcal)} kcal</span><span>P ${format(value.protein)} g</span><span>G ${format(value.carbs)} g</span><span>L ${format(value.fat)} g</span></div><ul>${(recipe.ingredients || []).map(item => `<li>${escapeHtml(food(item.foodId || item.food)?.name || item.foodId || item.food || "Aliment")} — ${format(item.grams)} g</li>`).join("")}</ul><div class="modal-actions"><button type="button" class="secondary-button" id="closeRecipe">Fermer</button><button type="button" class="primary-button" id="addRecipe">Ajouter au journal</button></div>`); byId("closeRecipe").addEventListener("click", closeModal); byId("addRecipe").addEventListener("click", () => { (recipe.ingredients || []).forEach(item => addFood(item.foodId || item.food, item.grams, "lunch")); closeModal(); toast("Recette ajoutée au déjeuner.", "success"); }); }
function openRecipeCreator() { const options = foods().map(item => `<option value="${item.id}">${escapeHtml(item.name)}</option>`).join(""); openModal(`<div class="modal-header"><h2>Créer une recette</h2></div><div class="form-group"><label for="recipeName">Nom</label><input id="recipeName" type="text" placeholder="Ex. Bowl protéiné"></div><div class="form-group"><label for="recipeFood">Aliment</label><select id="recipeFood">${options}</select></div><div class="form-group"><label for="recipeGrams">Quantité (g)</label><input id="recipeGrams" type="number" min="1" value="100"></div><p>V1 : crée une recette à un ingrédient, extensible ultérieurement.</p><div class="modal-actions"><button type="button" class="secondary-button" id="cancelRecipe">Annuler</button><button type="button" class="primary-button" id="saveRecipe">Enregistrer</button></div>`); byId("cancelRecipe").addEventListener("click", closeModal); byId("saveRecipe").addEventListener("click", () => { const name = byId("recipeName").value.trim(); const foodId = byId("recipeFood").value; const grams = number(byId("recipeGrams").value); if (!name || !foodId || grams <= 0) return toast("Nom, aliment et quantité sont requis.", "error"); state.recipes.push({ id: id("recipe"), name, emoji: food(foodId)?.emoji || "🍳", category: "Personnalisée", ingredients: [{ foodId, grams }] }); saveState(); render(); closeModal(); toast("Recette enregistrée.", "success"); }); }
function generateDay() { const available = foods(); if (!available.length) return toast("Base d'aliments indisponible.", "error"); const protein = available.filter(item => number(item.protein) >= 15); const carbs = available.filter(item => number(item.carbs) >= 15); const vegetables = available.filter(item => /légumes|fruits/i.test(item.category || "")); const goal = targets(); const day = newDay(); const pick = list => list[Math.floor(Math.random() * list.length)] || available[0]; const add = (meal, item, grams) => day[meal].push({ id: id("meal"), foodId: item.id, grams: round(grams) }); [["breakfast", .25], ["lunch", .35], ["snack", .1], ["dinner", .3]].forEach(([meal, fraction]) => { const target = goal.calories * fraction; const main = pick(protein); const starch = pick(carbs); const vegetable = pick(vegetables.length ? vegetables : available); add(meal, main, Math.max(80, target * .45 / Math.max(1, main.kcal) * 100)); add(meal, starch, Math.max(60, target * .4 / Math.max(1, starch.kcal) * 100)); add(meal, vegetable, 120); }); state.journal[dateKey()] = day; saveState(); render(); toast("Journée générée à partir de tes objectifs.", "success"); }
function generateWeek() { for (let index = 0; index < 7; index += 1) { const previous = state.journal[dateKey()]; const mealDay = newDay(); MEALS.forEach(meal => { mealDay[meal] = (previous?.[meal] || []).map(item => ({ ...item, id: id("plan") })); }); if (!MEALS.some(meal => mealDay[meal].length)) { const available = foods(); const item = available.find(food => number(food.protein) >= 15) || available[0]; if (item) MEALS.forEach(meal => mealDay[meal].push({ id: id("plan"), foodId: item.id, grams: meal === "snack" ? 100 : 180 })); } state.planner[index].meals = mealDay; } saveState(); render(); toast("Planning hebdomadaire généré.", "success"); }
function saveProfile() { const p = state.profile; const values = { name: "profileName", age: "profileAge", sex: "profileSex", height: "profileHeight", weight: "profileWeight", bodyFat: "profileBodyFat", chest: "profileChest", waist: "profileWaist", hips: "profileHips", arm: "profileArm", thigh: "profileThigh", neck: "profileNeck", trainingDays: "profileTraining", activity: "profileActivity", targetWeight: "profileTargetWeight", targetBodyFat: "profileTargetBodyFat", deficit: "profileDeficit", proteinPerKg: "proteinTarget", fatPerKg: "fatTarget", budget: "profileBudget", store: "profileStore" }; Object.entries(values).forEach(([key, target]) => { const node = byId(target); p[key] = ["profileName", "profileSex", "profileStore", "profileActivity"].includes(target) ? node.value : number(node.value, p[key]); }); p.goal = document.querySelector('input[name="profileGoal"]:checked')?.value || p.goal; p.preferences = { autoGenerate: byId("preferenceAutoGenerate").checked, budgetOptimization: byId("preferenceBudgetOptimization").checked, highProtein: byId("preferenceHighProtein").checked }; saveState(); render(); toast("Profil et objectifs enregistrés.", "success"); }
function bindEvents() { document.querySelectorAll("[data-page]").forEach(node => node.addEventListener("click", event => { event.preventDefault(); navigate(node.dataset.page); })); byId("mobileMenuButton")?.addEventListener("click", () => document.querySelector(".sidebar")?.classList.toggle("mobile-open")); byId("modalCloseButton")?.addEventListener("click", closeModal); byId("modalOverlay")?.addEventListener("click", event => { if (event.target === event.currentTarget) closeModal(); }); document.addEventListener("keydown", event => { if (event.key === "Escape") closeModal(); }); ["quickAddButton", "addMealButton", "journalAddButton"].forEach(key => byId(key)?.addEventListener("click", () => openFoodPicker())); ["generateDayButton", "emptyGenerateButton"].forEach(key => byId(key)?.addEventListener("click", generateDay)); byId("createRecipeButton")?.addEventListener("click", openRecipeCreator); byId("recipeSearch")?.addEventListener("input", renderRecipes); byId("recipeGoalFilter")?.addEventListener("change", renderRecipes); byId("generateWeekButton")?.addEventListener("click", generateWeek); byId("clearPlannerButton")?.addEventListener("click", () => { if (window.confirm("Réinitialiser le planning ?")) { state.planner = defaultPlanner(); saveState(); render(); } }); byId("saveProfileButton")?.addEventListener("click", saveProfile); document.addEventListener("click", event => { const button = event.target.closest("button"); if (!button) return; if (button.dataset.editItem) openEditPicker(button.dataset.meal, button.dataset.editItem); if (button.dataset.removeItem) { removeFood(button.dataset.meal, button.dataset.removeItem); toast("Aliment supprimé.", "success"); } if (button.dataset.recipeDetail) openRecipeDetail(button.dataset.recipeDetail); if (button.dataset.recipeAdd) openRecipeDetail(button.dataset.recipeAdd); if (button.dataset.plannerAdd) openFoodPicker({ meal: button.dataset.plannerAdd, plannerDay: number(button.dataset.plannerDay) }); }); }
function init() { bindEvents(); render(); if (state.profile.preferences.autoGenerate && !Object.keys(state.journal).includes(dateKey())) generateDay(); }
document.addEventListener("DOMContentLoaded", init, { once: true });


